name: demo
description: A Flutter APP.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_swiper: ^1.1.6
  dio: ^2.1.3
  flutter_webview_plugin: ^0.3.5
  cached_network_image: ^0.8.0
  shared_preferences: ^0.5.2
  flutter_staggered_grid_view: ^0.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/type_channelplane.png
    - images/type_district.png
    - images/type_food.png
    - images/type_hotel.png
    - images/type_huodong.png
    - images/type_shop.png
    - images/type_sight.png
    - images/type_ticket.png
    - images/type_travelgroup.png
    - images/type_channelgroup.png
    - images/type_channelgs.png
    - images/type_channeltrain.png
    - images/type_cruise.png
    - images/ln_food.png
    - images/ln_guide.png
    - images/ln_oneday.png
    - images/ln_ticket.png
    - images/ln_weekend.png
    - images/grid-nav-items-flight.png
    - images/grid-nav-items-hotel.png
    - images/grid-nav-items-travel.png
    - images/sub_nav_credit.png
    - images/sub_nav_exchange.png
    - images/sub_nav_freetravel.png
    - images/sub_nav_guide.png
    - images/sub_nav_lipin.png
    - images/sub_nav_more.png
    - images/sub_nav_play.png
    - images/sub_nav_shopping.png
    - images/sub_nav_visa.png
    - images/sub_nav_wifi.png
    - images/bed.png
    - images/loading_logo.png
